- name: Secure VM Configuration
  hosts: virtualmachines
  become: yes
  gather_facts: yes

  pre_tasks:
  # Gather facts
  - name: Gather facts on listening ports
    community.general.listen_ports_facts:

  vars:
    node_exporter_version: 1.5.0

  roles:
  # Security
    - base
    - firewalld
    - robertdebock.fail2ban
    - rkhunter
    - lynis
    - linux_malware_detect
  # Monitoring
    - node_exporter
    - prometheus



