global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      monitor: 'example'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/prometheus.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['{{ hostvars[inventory_hostname].prometheus_url }}']
    basic_auth:
      username: prometheus
      password: "{{ prometheus_basic_auth_password }}""

  - job_name: '{{ hostvars[inventory_hostname].ansible_host }}'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/prometheus.crt
    static_configs:
      - targets: ['{{ hostvars[inventory_hostname].node_exporter_url }}']
    basic_auth:
      username: prometheus
      password: "{{ prometheus_basic_auth_password }}""
